### ISSUE TITLE
Completely black renders

### ISSUE THREAD

**Issue by shankarsivarajan** [bsavery/BlenderPythonRenderer#31]
I tried rendering the default startup scene (Blender 3.0.1, Windows 10), and the render is all black.
![BPR_test](https://user-images.githubusercontent.com/16606427/155230259-b07b1ee9-5caa-4f1b-9eac-2034135ed67f.png)
It didn't raise any errors though, and increasing the intensity of the light didn't seem to do anything.
Could you please share an example of a scene that works for you?

**Comment by bsavery** [comment]
https://github.com/bsavery/BlenderPythonRenderer/tree/main/examples

Can you open the blender system console and see if there's any errors there?

**Comment by shankarsivarajan** [comment]
No errors, but on the first render there is a warning:

```
[Taichi] version 0.9.0, llvm 10.0.0, commit 0c432a37, win, python 3.9.7
call setup
[Taichi] Starting on arch=cuda
Total export 3.584152936935425
[W 02/22/22 20:26:47.050 5224] [D:/a/taichi/taichi/taichi/transforms/type_check.cpp:visit@142] [$6896] Local store may lose precision (target = u8, value = u8), at
6896
[W 02/22/22 20:26:47.052 5224] [D:/a/taichi/taichi/taichi/transforms/type_check.cpp:visit@142] [$7127] Local store may lose precision (target = u8, value = u8), at
7127
[W 02/22/22 20:26:47.053 5224] [D:/a/taichi/taichi/taichi/transforms/type_check.cpp:visit@142] [$7687] Local store may lose precision (target = u8, value = u8), at
7687
[W 02/22/22 20:26:47.053 5224] [D:/a/taichi/taichi/taichi/transforms/type_check.cpp:visit@142] [$9019] Local store may lose precision (target = u8, value = u8), at
9019
[W 02/22/22 20:26:47.055 5224] [D:/a/taichi/taichi/taichi/transforms/type_check.cpp:visit@67] [$10257] Atomic add (i32 to u32) may lose precision, at

[W 02/22/22 20:26:47.062 5224] [D:/a/taichi/taichi/taichi/transforms/type_check.cpp:visit@142] [$6896] Local store may lose precision (target = u8, value = u8), at
6896
[W 02/22/22 20:26:47.063 5224] [D:/a/taichi/taichi/taichi/transforms/type_check.cpp:visit@142] [$7127] Local store may lose precision (target = u8, value = u8), at
7127
[W 02/22/22 20:26:47.065 5224] [D:/a/taichi/taichi/taichi/transforms/type_check.cpp:visit@142] [$7687] Local store may lose precision (target = u8, value = u8), at
7687
[W 02/22/22 20:26:47.069 5224] [D:/a/taichi/taichi/taichi/transforms/type_check.cpp:visit@142] [$9019] Local store may lose precision (target = u8, value = u8), at
9019
Total render 12.15920352935791
```

Subsequent renders don't have this.
```
call setup
Total export 1.9710016250610352
Total render 9.001036882400513
```

**Comment by shankarsivarajan** [comment]
What version of ```taichi``` are you using?

**Comment by bsavery** [comment]
I have 0.8.X (I think 0.8.6) I haven't tested with taichi 0.9.0 yet.

Also this line https://github.com/bsavery/BlenderPythonRenderer/blob/6d7ff4e5ee7cf69bded451399877d12e15ed9936/render/render.py#L31

Can be set to use ti.vulkan or ti.cuda I think depending on your GPU.  Might make a difference.

**Comment by shankarsivarajan** [comment]
The example scenes both work as expected with Blender 3.5, Taichi 1.5, on Windows 10.

The problem was that I didn't have a light in the scene: the default point light is not recognized. I needed to add a mesh object, and add a Principled shader with emission _before_ changing the render engine to BPR. I also needed to close and reopen the file before rendering.
